### PR TITLE
add python 3.12

### PR DESCRIPTION
**Pull request by michaelbrewer**
AWS added support for Python 3.12

- https://github.com/aws/aws-sdk-js-v3/releases/tag/v3.451.0
- https://github.com/aws/aws-cdk/releases/tag/v2.109.0

### CODE REVIEW

**Comment by maxday** [comment]
Thanks for your contribution! I'll merge this as soon as the runtime will be released!

**Review by maxday — APPROVED** [review]

**Comment by maxday** [comment]
Hey @michaelbrewer 
Any chance you could add the base image? Otherwise I can add a commit on your PR let me know :)
Thanks!

**Comment by fiserv-plat-eng** [comment]
Will do that now.

**Comment by michaelbrewer** [comment]
Done @maxday

**Comment by GrahamCampbell** [comment]
3.12 is now GA.

**Review by maxday — APPROVED** [review]

**Pull request merged**
