### PR TITLE
add Java 21 (with and without Snapstart)

### PR DESCRIPTION
**Pull request by jreijn**
This PR adds support for Java 21 (with and without Lambda Snapstart)

https://aws.amazon.com/about-aws/whats-new/2023/11/aws-lambda-support-java-21/
https://github.com/aws/aws-cdk/releases/tag/v2.109.0

### CODE REVIEW

**Comment by maxday** [comment]
Amazing! I was about to write those! 
Thank you so much! Let me run some quick tests but it should be live tomorrow!

**Review by maxday — APPROVED** [review]

**Comment by maxday** [comment]
It seems that java:21 is not based on centos anymore (so `yum` is not installed)
would you be able to fix that and use `dnf` instead? You have an example here: 
https://github.com/maxday/lambda-perf/blob/main/s3-uploader/runtimes/rust_on_provided_al2023/Dockerfile#L7
Otherwise I can create a PR on your repo as well, let me know :)

**Comment by jreijn** [comment]
@maxday ah sorry I did not notice that! I will take a look and fix it!

**Comment by jreijn** [comment]
@maxday I've updated both Dockerfiles with the use of dnf. I've tested both Dockerfiles by running a `docker build .` locally and they seem to build fine now. Let me know if you spot any other issues!

**Comment by maxday** [comment]
All good now! 🥳  Thanks!

**Review by maxday — APPROVED** [review]

**Pull request merged**
